### ISSUE TITLE
Add content on the new Photos feature

### ISSUE THREAD

**Issue by skambo** [onaio/help#204]
First version of photos is being released possibly on Monday Oct 31st. Users should be informed of the limitations and workarounds.

Some workaround will be necessary e.g. an un-cropped image cannot be downloaded and also how to get the full-size images.

Ref: https://github.com/onaio/zebra/pull/4674#issuecomment-256641765

Content can/should be updated when https://github.com/onaio/zebra/issues/4694 is closed.

**Comment by rowo** [comment]
The limitation is the photos tab only shows cropped and lower resolution versions of the original images.

The workaround to download the full size image from the Ona website is to find the submission in the Table (or Map single submission popup), and click on the image there to get the full size version.

**Comment by faith-mutua** [comment]
@rowo, well noted. I will start working on this today

**Comment by faith-mutua** [comment]
The content is ready and there's a PR ready for review https://github.com/onaio/help/pull/207

**Comment by rowo** [comment]
@faith-mutua so @pld made some advancements and the cropping is no longer an issue. Instead, the images are being letter boxed to fill up a square so that the entire image gets shown. The downside to this is downloaded images will have black letter-boxing and reduced resolution. The full size, un-letter-boxed images will still be available by going to the Map and Table tabs.

This shouldn't be noticeable in the gallery or when the image is light-boxed though since we'll make the background on those pages black.

**Comment by rowo** [comment]
Correction, the image is still being cropped... in a sense. It's being resized down. Which I guess is resized to a lower resolution (longest edge down to 1024px).

**Comment by pld** [comment]
I wouldn't call that cropped, for me crop always implies removing part of
the image

**Comment by faith-mutua** [comment]
Thanks @rowo, @pld I will edit the document accordingly.

**Comment by rowo** [comment]
@faith-mutua I think I already changed it on https://github.com/onaio/help/pull/207
