### ISSUE TITLE
Your First Project guide is a bit weak

### ISSUE THREAD

**Issue by rowo** [onaio/help#208]
To me, "Your First Project" is about getting started and should be about how to get form on odk collect in 15 minutes. Is there a way we can add some content about doing a quick form there instead of the long XLSForm authoring guide? Also maybe remove the stuff about signing up/in cause that's pretty basic and in the way for that guide. Thoughts, ideas @msschroeder @faith-mutua @bmalina ?

**Comment by msschroeder** [comment]
@rowo I think the first portion of the guide up to signing up for your account is good to keep. Whether we keep the signing in/project, I think depends on the structure of the guide, but they could definitely be shortened to reference the longer guide. For a quick form, I guess that would depend on what you want to show the user, because a short form is referenced in the xlsform guide with basic useful questions types (text, number, image, GPS, select_one, select_multiple). We could  include a similar section to the [Basics](https://help.ona.io/guides/forms/#basics) of the xlsforms and provide a link to a form. 

However, were you thinking about changing the content for the last three section related to collection on ODK or Enketo? Did you want to include the steps for ODK step up in this guide as well?  I think you will have to reference the guide on ODK and Enketo regardless because the step by step guide for use is so detailed and a simplified (especially for a new user) may not be as useful..

**Comment by rowo** [comment]
Agree with your points. The main thing is we need somewhere to point people that's basically step=by-step, get a form out to Enketo/ODK Collect in 15 minutes. Perhaps it can be added to the beginning of the New to Ona guide.

So instead of a whole section on Signing in/logging in, it just says "[Log in](#) to your Ona account, then create a project by clicking the top right *New Project* button" With screenshot, but without a full paragraph explanations. And pointing the link for login to somewhere else. Then, put in the Basics tutorial, and add a link to the file at the top (this should be done anyways since it's pretty standard on technical tutorials — right now we have a Basics tutorial with no screenshots and no "completed" or "in progress" files). Then we can just do a few screens with the basic structure of the file, and link over to another guide for more info about what is going on in it. 

Then we talk about Adding the form, and show them where to find the Enketo link. And then as an option say you can get the form in ODK, but link somewhere else to how to set that up.

Then talk about where the data shows up. Another key is that all screenshots and examples use this same form.

I think that would be a pretty straightforward guide that would get someone immersed right away.

**Comment by msschroeder** [comment]
@rowo I have updated the google document. Please review. If okay, I can convert to markdown and create a pull request

Google Doc:https://docs.google.com/a/ona.io/document/d/1_yaBKrhHQlSTqND4XTRLcZS6NWrg7_F8hMUwlugzPGc/edit?usp=sharing

**Comment by rowo** [comment]
@msschroeder made comments on the doc. After the changes should be good.

**Comment by msschroeder** [comment]
Closed with PR #229 and #230
