### ISSUE TITLE
Add content on Formbuilder

### ISSUE THREAD

**Issue by msschroeder** [onaio/help#209]
Reference [Core Issue 2111] (https://github.com/onaio/zebra/issues/2111)

**Comment by rowo** [comment]
@msschroeder @bmalina I think "form builder" with a space is correct and Kobo's use of "formbuilder" is incorrect since they/we aren't using it as a proper noun. I'm going based mainly on what Wufoo and Survey Monkey do. What do you think?

**Comment by rowo** [comment]
Had a quick chat with Peter. It could be just called as the form builder, or when used as a sort of proper noun it could be "Ona Form Builder".

**Comment by rowo** [comment]
@bmalina I made a few fixes, but here are additional stylistic recommendations after reading it over:
- [ ] I don’t like the shifts when using verbs. Those need to stay consistent. Example: Duplicate Questions vs. Grouping Questions in the same list. I think the -ing version is better for the help site since it puts the emphasis on the action rather than the noun being acted upon. Otherwise, words like "Duplicate" and "Group" can be read as nouns.
- [ ] Replace "Online formbuilder" with "Form builder" and "formbuilder" with "form builder". This is a typo in the UI, sorry if it's extra work.
- [ ] I started to fix the headers, but it was too much work. First, all of the items were nested under a "Form builder Functions" group, which is unnecessary. Second, the items after "Create a Form" don't seem to be in any order. There are too many items to be in a single list, so please divide them into groups so people can find what they are looking for easier.
- [ ] Make sure cases are consistent. Don't switch between title case and sentence case.This applies to the entire help site and something to discuss/decide with the support team, then fix throughout the site.
- [ ] When using links, we should try to avoid stuff like "go [here](#) to find xyz". You should rephrase the link so it's clear what the link goes to.

**Comment by bmalina** [comment]
@rowo I have made the recommended changes to the document.
I will use title case as we decide on the standard case to be used. This is what we have for the other guides on the site.
