### ISSUE TITLE
Replace form updates

### ISSUE THREAD

**Issue by rowo** [onaio/help#47]
- Put a line at the top to make it clear that there are two processes for replacing form whether a user has submissions or not. You have to assume users will land on a question without context or on the incorrect answer. This applies to both http://help.ona.io/faq/replacing-forms-without-submissions/ and http://help.ona.io/topics/replace-form-that-has-submissions/ is not in the FAQ
- We are adding a link from a tooltip (https://github.com/onaio/zebra/issues/1940). I guess I should link to both answers?
- http://help.ona.io/topics/replace-form-that-has-submissions/ is not in the FAQ. I'm not sure how someone navigates to it.

**Comment by rowo** [comment]
@smusula still don't see how to navigate to the replace form with submissions. I think because it's in a topic and not a FAQ.

**Comment by wilo99** [comment]
@rowo the ideal place would be as an FAQ, since you can't link an FAQ while its a file in the Topics folder. As such:
- I've moved the `replace form with submissions` markdown file to FAQ folder
- Renamed the file to a more recent date to have it next to `Form replace without submissions` when links are generated
